# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: votechain.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "votechain.Empty" do
  end
  add_message "votechain.Vote" do
    optional :voter_proof, :string, 1
    optional :race_id, :int32, 2
    optional :selection, :string, 3
  end
  add_message "votechain.Result" do
    optional :success, :bool, 1
    optional :message, :string, 2
  end
  add_message "votechain.Block" do
    optional :number, :int32, 1
    optional :parent, :string, 2
    optional :nonce, :int32, 3
    optional :capacity, :int32, 4
    repeated :votes, :message, 5, "votechain.Vote"
  end
  add_message "votechain.BlockNumber" do
    optional :number, :int32, 1
  end
end

module Votechain
  Empty = Google::Protobuf::DescriptorPool.generated_pool.lookup("votechain.Empty").msgclass
  Vote = Google::Protobuf::DescriptorPool.generated_pool.lookup("votechain.Vote").msgclass
  Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("votechain.Result").msgclass
  Block = Google::Protobuf::DescriptorPool.generated_pool.lookup("votechain.Block").msgclass
  BlockNumber = Google::Protobuf::DescriptorPool.generated_pool.lookup("votechain.BlockNumber").msgclass
end
