# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed451ac053e8d16ee406265474ff050c87d2584b0d0dd0b2069464d65cff26d2eed6a6554888727bd9f750eae2fb9c5becc760b8afd0d31e38f4a67c73362a80

test:
  secret_key_base: af05bc35c48fe26419c2474dcdb11f056c4e2a9144c332e08fad9d8e4436af142959350b80d1d2ca514a5b54c20c2b62de671d9a36e5f4861a23ee4002852679

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
